version: '3'

services:
  web: 
    image: golang:1.11.4-alpine
    volumes:
      - .:/go/src/go-with-compose
      - ~/go/bin:/go/src
    working_dir: /go/src/go-with-compose
    command: go run main.go
    ports: 
      - 8080:8080
    depends_on:
      - mysql
    links:
      - mysql
    environment: 
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_PASS=12345"
    networks: 
      - mynet

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment: 
      -  MYSQL_ROOT_PASSWORD=12345
      -  MYSQL_DATABASE=chat
    volumes: 
      - ./data:/var/lib/mysql
    networks: 
      - mynet
networks: 
  mynet:
    driver: "bridge"